items:
    label: Item
    view:
        list: $/arteriaweb/catalog/models/item/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/arteriaweb/catalog/models/item/fields.yaml
        list: $/arteriaweb/catalog/models/item/columns.yaml
